//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int ID { get; set; }
        public string SentID { get; set; }
        public string ToID { get; set; }
        public int Status { get; set; }
    
        public virtual FriendsStatu FriendsStatu { get; set; }
        public virtual User UserSendID { get; set; }
        public virtual User UserToID { get; set; }
    }
}
