//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostRep
    {
        public int ID { get; set; }
        public int PostID { get; set; }
        public int Rep { get; set; }
        public string UserID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public virtual PostRep PostRep1 { get; set; }
        public virtual PostRep PostRep2 { get; set; }
    }
}
